# Site settings
title: Linkify
email: info@example.com
website: nfrasser.com
websiteurl: https://nfrasser.com
description: > # this means to ignore newlines until "baseurl:"
  Linkify is a JavaScript plugin. Use Linkify to find links in plain-text and
  convert them to HTML &lt;a&gt; tags. It automatically highlights URLs,
  #hashtags, @mentions and more.
url: "https://linkify.js.org" # the base hostname & protocol for your site
github_username: nfrasser/linkifyjs
version: "4.3.1"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-coffeescript
  - jekyll-sitemap

exclude:
  - node_modules
